### ISSUE TITLE
Exception on start

### ISSUE THREAD

**Issue by mikeodr** [drums-project/drums_ros#2]
Hi Mani,

I'm trying to use the drums_ros package and getting the following on start:

``` python
[INFO][2128.159000][/drumsros]: Ros graph monitor started.
[INFO][2129.089000][/drumsros]: Event: host, new, dev-vm-modriscoll-trusty-ws, 
[ERROR][2129.119000][/drumsros]: Unable to start the latency monitoring task for                     `dev-vm-modriscoll-trusty-ws:dev-vm-modriscoll-trusty-ws`
[INFO][2129.119000][/drumsros]: Event: host, new, dev-vm-modriscoll-trusty-ws.local, 
Exception in thread Thread-7:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/home/administrator/workspace/autonomy_ws/src/drums_ros/scripts/drums_ros.py", line 170, in run
    self.add_new_host(host, meta)
  File "/home/administrator/workspace/autonomy_ws/src/drums_ros/scripts/drums_ros.py", line 83, in add_new_host
    h, host, self.callback, meta, True)
  File "/home/administrator/workspace/autonomy_ws/src/drums_ros/scripts/drums_ros.py", line 62, in _register_latency_task
    task = drumspy.DrumsLatency(src, DRUMS_PORT, target=dst, meta=meta)
  File "/home/administrator/workspace/autonomy_ws/src/drums_ros/src/drumspy/__init__.py", line 255, in __init__
    DrumsRESTBase.__init__(self, host, http_port, **kwargs)
  File "/home/administrator/workspace/autonomy_ws/src/drums_ros/src/drumspy/__init__.py", line 105, in __init__
    raise RuntimeError
RuntimeError
```

Any support would be appreciated as I'm fumbling though how to use this as the readme's are fairly empty.

**Comment by mikeodr** [comment]
So as discussed offline this appeared to have occurred due to having ros listening to the non-default interface. I can try to investigate in due course.

**Comment by mani-monaj** [comment]
For the reference, this is a quick start guide which will eventually be moved to the docs: https://github.com/drums-project/drums_ros/blob/indigo-devel/quick_setup.md
